#get the node number in the *.stats file from line with "District"
cat kmer.stats
#format the histogram file generated by jellyfish
perl ../Bin/format.pl kmer.histo kmer.xls 999937	#999937 is the node number from kmer.stats file
#estimate the charicteristics of genome
perl ../Bin/GenomeAnalysis.pl kmer.xls 17 16800000	#16800000 is the total k-mer number from kmer.stats file
